# Continious Integration Configuration File for KURI MBZIRC Challenge 3 Package
# Author: Tarek Taha
# Date  : 29/05/2016
sudo: required
dist: trusty
language: generic
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    recipients:
    - tarek.taha@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  global:
    # Some Global variables can go here
    - GLOBAL_VAR="global_var"
  matrix:
    - ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="jade"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
# Install prerequisites and/or dependencies required by the system
before_install: 
  - cmake --version
  - find /usr/share -iname "*Eigen*.cmake"
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME on $ROS_DISTRO"
  - sudo -E sh -c 'echo "deb $ROS_REPOSITORY_PATH `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-wstool python-catkin-tools
  - sudo apt-get install -y libcgal-dev
  - sudo rosdep init
  - rosdep update
# Use this to install any prerequisites or dependencies necessary to run your build
install: 
  # Create workspace
  - mkdir -p ~/ros/kuri_catkin_ws/
  - cd ~/ros/kuri_catkin_ws/
  - wstool init src
  - wstool merge -t src https://raw.githubusercontent.com/kuri-kustar/kuri_mbzirc_challenge_3/master/mbzirc_challenge3.rosinstall
  - wstool update -t src
  - rosdep install -y -r --from-paths src --ignore-src --rosdistro $ROS_DISTRO
# Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
before_script: 
- source /opt/ros/$ROS_DISTRO/setup.bash
# All commands must exit with code 0 on success. Anything else is considered failure
script:
- catkin_make  --pkg kuri_msgs --cmake-args -DCONFIG=ros_sitl_simple
- source devel/setup.bash
- rospack profile
- catkin_make --cmake-args -DCONFIG=ros_sitl_simple
